# Generated by Django 4.0.1 on 2022-01-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default=2, max_length=1024),
            preserve_default=False,
        ),
    ]
